from pathlib import Path

from fpdf import FPDF

from app.config import BASE_DIR
from app.schemas import ComicPanel


class ComicPDF(FPDF):

    def footer(self):
        self.set_y(-15)

        self.set_font(
            "Helvetica",
            size=8,
        )

        self.cell(
            0,
            10,
            "Generated by ComicCraft",
            align="C",
        )


def get_local_image(
    image_path: str,
) -> Path:

    if image_path.startswith("/static/"):
        relative_path = image_path.replace(
            "/static/",
            "",
            1,
        )

        return (
            BASE_DIR
            / "static"
            / relative_path
        )

    return Path(image_path)


def save_pdf(
    layout: list[ComicPanel],
) -> str:

    output_dir = (
        BASE_DIR
        / "static"
        / "exports"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    filename = "comiccraft_comic.pdf"

    output_path = (
        output_dir
        / filename
    )

    pdf = ComicPDF()

    pdf.set_auto_page_break(
        auto=True,
        margin=15,
    )

    for panel in layout:

        pdf.add_page()

        pdf.set_font(
            "Helvetica",
            "B",
            18,
        )

        pdf.cell(
            0,
            12,
            f"Panel {panel.panel_number}: {panel.title}",
            ln=True,
        )

        image_file = get_local_image(
            panel.image_path
        )

        if image_file.exists():

            pdf.image(
                str(image_file),
                x=15,
                y=35,
                w=180,
            )

            pdf.ln(120)

        pdf.set_font(
            "Helvetica",
            "B",
            12,
        )

        pdf.cell(
            0,
            8,
            "Scene Description",
            ln=True,
        )

        pdf.set_font(
            "Helvetica",
            size=10,
        )

        pdf.multi_cell(
            0,
            6,
            panel.scene_description,
        )

        pdf.ln(4)

        pdf.set_font(
            "Helvetica",
            "B",
            12,
        )

        pdf.cell(
            0,
            8,
            "Caption",
            ln=True,
        )

        pdf.set_font(
            "Helvetica",
            size=10,
        )

        pdf.multi_cell(
            0,
            6,
            panel.caption,
        )

        pdf.ln(4)

        pdf.set_font(
            "Helvetica",
            "B",
            12,
        )

        pdf.cell(
            0,
            8,
            "Narration",
            ln=True,
        )

        pdf.set_font(
            "Helvetica",
            size=10,
        )

        pdf.multi_cell(
            0,
            6,
            panel.narration,
        )

    pdf.output(
        str(output_path)
    )

    return f"/static/exports/{filename}"